### ISSUE TITLE
Cannot go directly to login page

### ISSUE THREAD

**Issue by NotBambi** [celinaberg/BitFit#4]
Attempting to navigate to the login page without clicking a link elsewhere gives this fun little error:

`Error: ENOENT: no such file or directory, stat 'client/index.html' at Error (native)`

**Comment by RhysBower** [comment]
@tiara-allidina7 Are you able to reproduce this? It looks like this may not be an issue on the production server.

**Comment by RhysBower** [comment]
Login page is removed with CWL integration so closing this issue.
