### ISSUE TITLE
Add a Topic Doesn't update topic list

### ISSUE THREAD

**Issue by RhysBower** [celinaberg/BitFit#40]
From Celina

> It appears that it is actually adding topics correctly, you just have to refresh the screen after clicking “Add Topic”.

**Comment by RhysBower** [comment]
@tiara-allidina7 I would look at the add topic code and make sure it updates the in memory list of topics.

**Comment by RhysBower** [comment]
The problem should be in one of the controllers in the `/client/app/admin` part of the codebase.

**Comment by celinaberg** [comment]
The "Add Topic" seems to persist the change to the database.  I just have to click somewhere else on the screen to see change reflected in the GUI.  I feel like this refresh _**should**_ happen when I click on the "Add Topic"

**Comment by RhysBower** [comment]
This will be fixed with #49
