### ISSUE TITLE
Secure execution of student code

### ISSUE THREAD

**Issue by RhysBower** [celinaberg/BitFit#41]
My current idea is to use docker to execute the student code in a secure environment.

There are several packages to interact with Docker that can be evaluated for our needs.
- [dockerode](https://github.com/apocas/dockerode)
- [docker-api](https://github.com/AgustinCB/docker-api)

**Comment by alythobani** [comment]
Merged to master on August 15. Docker didn't work out well (too slow) so we run the student code while sudo'd as another user on the VM with fewer permissions instead.
